update=Sun 12 Apr 2015 17:20:24 MSK
version=1
last_client=eeschema
[cvpcb]
version=1
NetITyp=0
NetIExt=.net
PkgIExt=.pkg
NetDir=
LibDir=
NetType=0
[cvpcb/libraries]
EquName1=devcms
[general]
version=1
[pcbnew]
version=1
PadDrlX=394
PadDimH=787
PadDimV=787
BoardThickness=630
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=150
LastNetListRead=voltage_regulator.net
[pcbnew/libraries]
LibDir=
LibName1=../../../kicad-components/mod_kicad/LFcomponents
LibName2=../../../kicad-components/mod_kicad/LFconnectors
LibName3=../../../kicad-components/mod_kicad/LFsmd_case
LibName4=../../../kicad-components/mod_kicad/LFtransformator
[eeschema]
version=1
LibDir=
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=../../../kicad-components/library_kicad/LFbutton
LibName2=../../../kicad-components/library_kicad/LFcapitors
LibName3=../../../kicad-components/library_kicad/LFcomponents
LibName4=../../../kicad-components/library_kicad/LFconnectors
LibName5=../../../kicad-components/library_kicad/LFdiod
LibName6=../../../kicad-components/library_kicad/LFpower
LibName7=../../../kicad-components/library_kicad/LFresistor
LibName8=../../../kicad-components/library_kicad/LFtransformator
LibName9=../../../kicad-components/library_kicad/LFtransistor
