update=Mon 11 Aug 2014 12:20:37 MSK
version=1
last_client=eeschema
[cvpcb]
version=1
NetITyp=0
NetIExt=.net
PkgIExt=.pkg
NetDir=
LibDir=
NetType=0
[cvpcb/libraries]
EquName1=devcms
[general]
version=1
[pcbnew]
version=1
PadDrlX=394
PadDimH=630
PadDimV=630
BoardThickness=630
SgPcb45=1
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=50
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=100
LastNetListRead=module_adc.net
[pcbnew/libraries]
LibDir=
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=valves
LibName9=led
LibName10=dip_sockets
LibName11=../../SafeDuino/trunk/kicad/mod_kicad/LFcomponents
LibName12=../../SafeDuino/trunk/kicad/mod_kicad/LFconnectors
LibName13=../../SafeDuino/trunk/kicad/mod_kicad/LFtransformator
LibName14=../../SafeDuino/trunk/kicad/mod_kicad/LFsmd_case
[eeschema]
version=1
LibDir=/usr/share/kicad/library
NetFmtName=
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=../../SafeDuino/trunk/kicad/library_kicad/LFcapitors
LibName2=../../SafeDuino/trunk/kicad/library_kicad/LFcomponents
LibName3=../../SafeDuino/trunk/kicad/library_kicad/LFconnectors
LibName4=../../SafeDuino/trunk/kicad/library_kicad/LFdiod
LibName5=../../SafeDuino/trunk/kicad/library_kicad/LFresistor
LibName6=../../SafeDuino/trunk/kicad/library_kicad/LFtransformator
LibName7=../../SafeDuino/trunk/kicad/library_kicad/LFbutton
