update=Ср 22 июн 2016 23:11:27
version=1
last_client=kicad
[cvpcb]
version=1
NetITyp=0
NetIExt=.net
PkgIExt=.pkg
NetDir=
LibDir=
NetType=0
[cvpcb/libraries]
EquName1=devcms
[general]
version=1
[pcbnew]
version=1
PadDrlX=394
PadDimH=787
PadDimV=787
BoardThickness=630
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=150
LastNetListRead=voltage_regulator.net
[pcbnew/libraries]
LibDir=
LibName1=../../../kicad-components/mod_kicad/LFcomponents
LibName2=../../../kicad-components/mod_kicad/LFconnectors
LibName3=../../../kicad-components/mod_kicad/LFsmd_case
LibName4=../../../kicad-components/mod_kicad/LFtransformator
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=PS15100-rescue
LibName2=../../../kicad-components/library_kicad/LFbutton
LibName3=../../../kicad-components/library_kicad/LFcapitors
LibName4=../../../kicad-components/library_kicad/LFcomponents
LibName5=../../../kicad-components/library_kicad/LFconnectors
LibName6=../../../kicad-components/library_kicad/LFdiod
LibName7=../../../kicad-components/library_kicad/LFpower
LibName8=../../../kicad-components/library_kicad/LFresistor
LibName9=../../../kicad-components/library_kicad/LFtransformator
LibName10=../../../kicad-components/library_kicad/LFtransistor
